sudo: requiered
services:
  - docker


before_install:
  - docker build -t spanas/docker-complex-udemy-test -f ./client/Dockerfile.dev ./client

script:
  - docker run spanas/docker-complex-udemy-test npm test -- --coverage

after_success:
  - docker build -t szympans/docker-complex-client ./client
  - docker build -t szympans/docker-complex-nginx ./nginx
  - docker build -t szympans/docker-complex-api ./server
  - docker build -t szympans/docker-complex-worker ./worker
  #Log into docker CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  #Push to dockerhub
  - docker push szympans/docker-complex-client
  - docker push szympans/docker-complex-nginx
  - docker push szympans/docker-complex-api
  - docker push szympans/docker-complex-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-complex-udemy"
  env: "DockerComplexUdemy-env"
  bucket_name: "elasticbeanstalk-us-east-2-565501007003"
  bucket_path: "docker-complex-udemy"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  